name: Deploy Actions
run-name: Upgrade version & Firebase Deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'back/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci && npm version patch && npm run build
      - name: firebase deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        working-directory: ./front
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TODOLIST_EUNUNG }}"
          projectId: todolist-eunung
          channelId: live


