name: Deploy Actions
run-name: Upgrade version & Firebase Deploy
on:
  push:
    branches:
      - github/actions
    paths-ignore:
      - 'back/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Move Directory
        run: |
          cd front
      - name: Check List files
        run: |
          ls
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci && npm version patch && npm run build
#      - name: firebase deploy
#        uses: FirebaseExtended/action-hosting-deploy@v0
#        with:
#          repoToken: "${{ secrets.GITHUB_TOKEN }}"
#          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
#          projectId: todolist-eunung
#          channelId: live


