name: deploy-actions
on:
  push:
    branches:
      - master
    paths:
      - 'front/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'upgrade version'
        uses: actions/checkout@v4
      - name: 'setup nodejs'
        uses: actions/setup-node@v3
        with:
          node-version: '20'
        run: npm ci && npm version patch && npm run build
      - name: 'firebase deploy'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: todolist-eunung
          channelId: live


